#!/bin/bash
set -eu

BASE=$(dirname $0)/../
CPU=$1
MEM=$2
DISK=$3
ARCH=$4
NODES=$5

# Perhaps make this always recreate the nodes for repeatability?
$BASE/scripts/register-nodes $CPU $MEM $DISK $NODES

deploy_kernel=$TRIPLEO_ROOT/deploy-ramdisk.kernel
deploy_ramdisk=$TRIPLEO_ROOT/deploy-ramdisk.initramfs
deploy_kernel_id=$(glance image-create --name bm-deploy-kernel --public \
    --disk-format aki < "$deploy_kernel" | awk ' / id / {print $4}')
deploy_ramdisk_id=$(glance image-create --name bm-deploy-ramdisk --public \
    --disk-format ari < "$deploy_ramdisk" | awk ' / id / {print $4}')

# While we can't mix hypervisors, having non-baremetal flavors will just
# confuse things.
nova flavor-delete m1.tiny || true
nova flavor-delete m1.small || true
nova flavor-delete m1.medium || true
nova flavor-delete m1.large || true
nova flavor-delete m1.xlarge || true

nova flavor-delete baremetal || true
nova flavor-create baremetal auto $2 $3 $1
# FIXME: for amd64, if cpu_arch is set for flavor, nova
# doesn't find suitable baremetal node (even if amd64 arch
# is set in heat template). Related to:
# https://bugs.launchpad.net/tripleo/+bug/1213967
#nova flavor-key baremetal set "cpu_arch"="$ARCH" \
nova flavor-key baremetal set \
    "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
    "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id"
